/**
 * Database row types — mirror the Supabase schema in supabase/migrations/001_schema.sql
 *
 * Keep these aligned with the SQL. When you add a column, add it here too.
 * Later this file can be auto-generated by `supabase gen types typescript`.
 */

export type FoodTag = "best" | "spicy" | "chef";

export type RestaurantRow = {
  id: string;
  slug: string;
  name: string;
  subtitle: string | null;
  rating: number | null;
  prep_time: string | null;
  created_at: string;
};

export type RestaurantTableRow = {
  id: string;
  restaurant_id: string;
  table_number: number;
  created_at: string;
};

export type MenuItemRow = {
  id: string;
  restaurant_id: string;
  name: string;
  description: string | null;
  category: string;
  price: number;
  veg: boolean;
  emoji: string | null;
  image_url: string | null;
  tags: string[];
  in_stock: boolean;
  display_order: number;
  created_at: string;
};

export type OrderRow = {
  id: string;
  restaurant_id: string;
  table_id: string | null;
  status: string;
  subtotal: number;
  gst: number;
  total: number;
  payment_method: string | null;
  created_at: string;
};

export type OrderItemRow = {
  id: string;
  order_id: string | null;
  menu_item_id: string | null;
  quantity: number;
  price: number;
};

/**
 * Loosely typed Supabase Database object.
 * Sufficient for our queries; can be replaced with the generated full schema later.
 */
export type Database = {
  public: {
    Tables: {
      restaurants: {
        Row: RestaurantRow;
        Insert: Partial<RestaurantRow> & Pick<RestaurantRow, "slug" | "name">;
        Update: Partial<RestaurantRow>;
      };
      restaurant_tables: {
        Row: RestaurantTableRow;
        Insert: Partial<RestaurantTableRow> &
          Pick<RestaurantTableRow, "restaurant_id" | "table_number">;
        Update: Partial<RestaurantTableRow>;
      };
      menu_items: {
        Row: MenuItemRow;
        Insert: Partial<MenuItemRow> &
          Pick<MenuItemRow, "restaurant_id" | "name" | "category" | "price">;
        Update: Partial<MenuItemRow>;
      };
      orders: {
        Row: OrderRow;
        Insert: Partial<OrderRow> & Pick<OrderRow, "restaurant_id">;
        Update: Partial<OrderRow>;
      };
      order_items: {
        Row: OrderItemRow;
        Insert: Partial<OrderItemRow> &
          Pick<OrderItemRow, "quantity" | "price">;
        Update: Partial<OrderItemRow>;
      };
    };
  };
};
